# GitHub Pages Configuration
title: "Pós-Doutorado Brenno Moura Naval"
description: "Repositório acadêmico com projetos e ferramentas de pesquisa"
baseurl: "/POS-DOUTORADO-BRENNO"
url: "https://brennomouranaval.github.io"

# Theme
theme: minima

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Include/Exclude
include:
  - gantt-chart

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - gantt-chart/index.html

# SEO
author: Brenno Moura Naval
social:
  - https://github.com/brennomouranaval